name: Lint and Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # Use the same version as in package.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use the same version as specified in engines in package.json
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier Check
        run: pnpm prettier

